### PR TITLE
cleanup and update  bzr2git.sh 

### PR DESCRIPTION
**Pull request by mdavidsaver**
Remove SF+HG scripts which are no longer needed.  Re-write bzr2git.sh to query launchpad.net for a list of BZR branches with changes and import all ~epics-core/epics-base/\* branches.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
@ralphlange I'd like to hear from you if I could break any Jenkins stuff by pushing changes to this repo.

**Comment by ralphlange** [comment]
Yes, you could.

**Comment by ralphlange** [comment]
There are three jobs on CloudBees syncing 3.14, 3.15 and 3.16, see:
https://openepics.ci.cloudbees.com/view/EPICS%20V3/

The job source is in the jenkins-jobs repo:
https://github.com/epics-base/jenkins-jobs/blob/master/templates/V3_Sync.yaml

**Comment by ralphlange** [comment]
The existing Jenkins jobs do one branch each and use the script `1bzr2git`, so this PR should be fine.

I would leave automatic syncing to the "official" repo limited to the official LP branches, as the GitHub development model has the feature branches in cloned repositories, not in the central one.

**Comment by mdavidsaver** [comment]
With the migration to git now complete, I don't think this is relevant anymore.

**Comment by ralphlange** [comment]
Move hgxgit to RIP?

**Comment by mdavidsaver** [comment]
Sure.  It has served its purpose.

**Comment by ralphlange** [comment]
Done.

**Pull request closed without merging**
